name: BV-RADS
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dcm2niix=1
  - dcm2bids=3.1
  - pydicom=2.4.4
  - numpy=1.25
  - pandas=2.1
  - nibabel=5.2
  - matplotlib=3.8
  - pip=23.3
  - scipy=1.11
